### ISSUE TITLE
Erro no pip install -e: "EntryPoint must be in 'name=module:attrs [extras]' format", 'checks = checks-py.cli:app')

### ISSUE THREAD

**Issue by labanca** [splor-mg/checks#2]
Tentando a instação com `pip install -e c:/projects/checks-py` o seguinte erro acontece:

```
ERROR: Exception:
Traceback (most recent call last):
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2936, in get_entry_map
    ep_map = self._ep_map
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2902, in __getattr__
    raise AttributeError(attr)
AttributeError: _ep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_internal\commands\install.py", line 452, in run
    installed = install_given_reqs(
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_internal\req\__init__.py", line 72, in install_given_reqs
    requirement.install(
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_internal\req\req_install.py", line 856, in install
    install_wheel(
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 725, in install_wheel
    _install_wheel(
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 559, in _install_wheel
    console, gui = get_entrypoints(distribution)
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 121, in get_entrypoints
    for entry_point in dist.iter_entry_points():
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 190, in iter_entry_points
    for group, entries in self._dist.get_entry_map().items():
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2938, in get_entry_map
    ep_map = self._ep_map = EntryPoint.parse_map(
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2610, in parse_map
    maps[group] = cls.parse_group(group, lines, dist)
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2588, in parse_group
    ep = cls.parse(line, dist)
  File "c:\projects\cc-checks-py-test\venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2566, in parse
    raise ValueError(msg, src)
ValueError: ("EntryPoint must be in 'name=module:attrs [extras]' format", 'checks = checks-py.cli:app')

```

**Comment by fjuniorr** [comment]
Não sei se é a mesma coisa mas no meu pc o erro foi diferente:

```
ERROR: For req: checks==0.0.0.post9000. Invalid script entry point: <ExportEntry checks = checks:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.
```

A correção no meu caso foi em `pyproject.toml`

```
[project.scripts]
-checks = "checks-py.cli:app"
+checks = "checks.cli:app"
```

**Comment by labanca** [comment]
O erro estava em: 

```
[project.scripts]
checks = "checks-py.cli:app"
```

O correto seria:

```
[project.scripts]
checks-py = "checks.cli:app"
```

**Comment by labanca** [comment]
@fjuniorr quando eu tenho de referenciar o check-py?

No caso eu coloquei `checks-py = "checks.cli:app"`, e funcionou, mas checks-py o nome do repositório e não do pacote. Isso daria problema? Onde esse entry point é utilizado?

**Comment by fjuniorr** [comment]
Em `checks = "checks.cli:app"` o `checks` é o nome do comando que vai estar disponível na linha de comando e o `checks.cli:app` é o "caminho" até o objeto `app` no módulo `checks.cli`.

O nome do repositório ser diferente do pacote não gera problemas além de confusão nossa (ie. podendo ser igual melhor, mas em casos igual esse que talvez a gente tenha um `checks-r` vale a confusão).
