### ISSUE TITLE
check installed_packages: conflito entre nome do pacote no github e do pacote instalado

### ISSUE THREAD

**Issue by labanca** [splor-mg/checks#5]
```Python
$ make extract
Checking python packages...
Required packages are missing: checks-py
Traceback (most recent call last):
  File "C:\projects\cc-cookie-checks-py\scripts\requirements.py", line 79, in <module>
    check_requirements()
  File "C:\projects\cc-cookie-checks-py\scripts\requirements.py", line 30, in check_requirements
    raise exceptions.MissingPackageError
exceptions.MissingPackageError
make: *** [Makefile:16: requirements] Error 1
```

O comando `installed-packages` hoje toma o nome do pacote presente na URL para realizar a verificação. No caso do `checks-py` o nome do pacote instalado é `checks` :

`git+https://github.com/splor-mg/checks-py.git@main`

```
$ pip list
Package                   Version
------------------------- --------------
annotated-types           0.7.0
attrs                     23.2.0
build                     1.2.1
certifi                   2024.6.2
chardet                   5.2.0
charset-normalizer        3.3.2
checks                    0.0.0.post9000

```

@fjuniorr caso você saiba algum workaround para esse tipo de situação. Somente ocorreu com esse pacote, pois ele não é instalado via `pip`.

**Comment by fjuniorr** [comment]
Eventualmente a gente pode migrar todas as nossas especificações de pacotes no git para o formato `packagename @ git+https://github.com/user/packagename.git` que é a nova recomendação[^1] e mudar a lógica de extração do nome do pacote.

Por enquanto alterei o nome do repo porque não é prioridade.

Vamos deixar esse issues aberto como lembrete. 

[^1]: Em https://github.com/pypa/pip/pull/11617 tem uma discussão com o histórico disso.
